name: .NET Core

on: [push, pull_request]

env:
    VERSION_NUMBER: 5.0.0.${{github.run_number}}

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

# 3.1 required for dotnet-property tool
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build Reason
      run: "echo ref: ${{github.ref}} event: ${{github.event_name}} version: $VERSION_NUMBER"

    - name: Install Tool
      run: dotnet tool install -g dotnet-property

    - name: Update Version
      run: dotnet property "**/version.props" Version:"$VERSION_NUMBER" PackageVersion:"$VERSION_NUMBER-timmy" AssemblyVersion:"$VERSION_NUMBER" FileVersion:"$VERSION_NUMBER" InformationalVersion:"$VERSION_NUMBER+$GITHUB_SHA"

    - name: Build Solution
      run: dotnet build --configuration Release

    - name: Package Nuget
      if: success() && startsWith(github.ref, 'refs/tags/v')
      run: dotnet pack --configuration Release --include-symbols --include-source --no-restore

    - name: Publish CI Packages
      if: success() && startsWith(github.ref, 'refs/tags/v')
      run: |
        for package in $(find -name "*.nupkg"); do
          echo "${0##*/}": Pushing $package...
          dotnet nuget push $package --source https://nuget.pkg.github.com/timbze/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        done
